#!/usr/bin/env bash
set -eu

# Read command line args
declare -r GIT_REPO=$1 SCRIPT_PATH=$2
# Read script args into an array.
declare -ra SCRIPT_ARGS=( ${RD_CONFIG_SCRIPT_ARGS:-} )

# Create a temporary workspace 
declare -r WORKSPACE=$(mktemp -d "/tmp/workspace.XXXX")
trap 'rm -r "$WORKSPACE"' EXIT ; # Clean up afterwards.

# Do work relative to the workspace.
cd "$WORKSPACE"

declare -r REPO_NAME=$(basename "$GIT_REPO" .git)
# Rewrite the URL to use the oauth2 token
declare -r GIT_URL=${GIT_REPO/https:\/\/github.com\//https://oauth2:${RD_CONFIG_GIT_TOKEN}@github.com/}


# If dryun, only print out commands that would be run.
if [[ "${RD_CONFIG_DRYRUN:-}" == true ]]
then
	cat <<-EOF
	# ===== dry run =====
	# git clone "$GIT_URL"
	# cd "${REPO_NAME}"
	# "$RD_CONFIG_SCRIPT_INVOKER" "$SCRIPT_PATH" ${SCRIPT_ARGS[@]:-}
	# ===================
	EOF
	#
else
	#
	# Check out the repository
	# 
	git clone "$GIT_URL"
	# 
	# Set new working directory relative to repository
	cd "${REPO_NAME}"
	# 
	# Execute the script
	#
	"$RD_CONFIG_SCRIPT_INVOKER" "$SCRIPT_PATH" "${SCRIPT_ARGS[@]:-}"
fi

# Done.
exit $?

