#!/usr/bin/env bash

echo "running: $0 $* ..."



echo $(tput setaf 1) " ___   _ _  _ ___  ___ ___ _  __"
echo $(tput setaf 2) "| _ \ | | | \| |   \| __/ __| |/ /"
echo $(tput setaf 3) "|   / |_| | .\` | |) | _| (__| ' < "
echo $(tput setaf 4) '|_|_\\___/|_|\_|___/|___\___|_|\_\'
echo ""
echo $(tput setaf 5) "          RUNDECK FTW!"$(tput sgr0)